# Generated by Django 4.1.4 on 2023-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='type',
            field=models.CharField(choices=[('pub', 'Pub'), ('resturant', 'Resturant'), ('cafe', 'Cafe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
    ]
