# Generated by Django 4.1.4 on 2023-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_establishment_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.FileField(null=True, upload_to='uploads/dp/'),
        ),
    ]
